parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''


doctrine:
    dbal:
        default_connection:     achat_centrale
        connections:
            achat_centrale:
                driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                host:         '%env(DATABASE_IP)%'
                user:         '%env(DATABASE_USER)%'
                password:     '%env(DATABASE_PWD)%'
                dbname:       "CENTRALE_ACHAT"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App



