security:
    encoders:
        App\Entity\Users:
            algorithm:            plaintext
            ignore_case:          false
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        users:
            entity:
                class: 'App\Entity\Users'
                property: 'usMail'
    firewalls:
        main:
            pattern: ^/
            logout:
                invalidate_session: true
                path: app_logout
                target: /login
            anonymous:    true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

